version: "3.7"

services:
  zookeeper:
    container_name: ars_zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: ars_kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CREATE_TOPICS=onewallet.aamsReport.v1:1:1
    depends_on:
      - zookeeper

  docker_example:
    container_name: docker_example
    image: com.example/docker-example:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka